size = 1.77
weigth = 59.25
gender = "m"

free_flyer = true
Tf=2
nb_samples = 60
optimal_control = 0

task= "arm_reaching"

active_joints = [
    "universe",
    "root_joint",
  #  "middle_lumbar_Z",
  # "middle_lumbar_X",
  # "middle_thoracic_Z",
   "right_shoulder_Z",
   "right_elbow_Z",
  ]

 
  
active_costs=[
  "min_joint_torque",  
  "min_torque_change", 
  "min_joint_acc", 
  "min_joint_vel",
  #"min_joint_jerk",  
  #"min_cartesian_acc",  
  #"min_cartesian_jerk" 
  ] 


groups_joint_torques = {all=true, group1 = ["right_shoulder_Z","right_elbow_Z"], group2 = ["right_shoulder_Z","right_elbow_Z"] } 



build_solver = false 

# default values
viewer = "meshcat"
solver="acados"#"fatrop"#"ipopt"#

external_forces=false#"linear_zmp_distance_forces_estimation"#""#"linear_zmp_distance_forces_estimation" #"optimal_forces_estimation"


cop_lim = [-0.05, 0.25]
qdi = {type = "array", size = 37, fill = 1e-3, deg2rad = true}
q_min = {type = "array", size = 37, fill = -360, deg2rad = true}
q_max = {type = "array", size = 37, fill = 360, deg2rad = true}
dq_lim = {type = "array", size = 37, fill = 720, deg2rad = true}
dqdi = {type = "array", size = 37, fill = 0, deg2rad = true}
n_tau = {type = "array", size = 37, fill = 200, deg2rad = false} # Can also remove the field deg2rad
n_dq = {type = "array", size = 37, fill = "pi", mult = "2", deg2rad = false}
n_ddq = {type = "array", size = 37, fill = "3*pi", deg2rad = false}
toto_to_bobo = {type = "SE3", rotation = "Identity", position = [0, 0, -0.4]}
L = {toto_to_bobo = {type = "SE3", rotation = "Identity", position = [0, 0, -0.4]}}
pyf = 0


